### ISSUE TITLE
直接运行会报target.view()出现错误，之后改成.reshape(),或者.contiguous().view(),的时候还会报下面第二个错误

### ISSUE THREAD

**Issue by Hans-2019** [liang8qi/Data2TextWithAuxiliarySupervision#1]
直接运行会报target.view()出现错误，之后改成.reshape(),或者.contiguous().view(),的时候还会报下面第二个错误

Traceback (most recent call last):
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 556, in <module>
    main()
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 548, in main
    train_model(model1, model2, fields, optim1, optim2, data_type, model_opt)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 297, in train_model
    train_stats, train_stats2 = trainer.train(train_iter, epoch, report_func)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Trainer.py", line 294, in train
    self._gradient_accumulation_basic_encdec(true_batchs, total_stats2, report_stats2, normalization)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Trainer.py", line 513, in _gradient_accumulation_basic_encdec
    batch_stats = self.train_loss2.sharded_compute_loss(
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Loss.py", line 136, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/modules/CopyGenerator.py", line 204, in _compute_loss
    target = target.view(-1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
改成.reshape(),或者.contiguous().view(),的时候
Traceback (most recent call last):
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 556, in <module>
    main()
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 548, in main
    train_model(model1, model2, fields, optim1, optim2, data_type, model_opt)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/train.py", line 297, in train_model
    train_stats, train_stats2 = trainer.train(train_iter, epoch, report_func)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Trainer.py", line 294, in train
    self._gradient_accumulation_basic_encdec(true_batchs, total_stats2, report_stats2, normalization)
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Trainer.py", line 513, in _gradient_accumulation_basic_encdec
    batch_stats = self.train_loss2.sharded_compute_loss(
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Loss.py", line 135, in sharded_compute_loss
    for shard in shards(shard_state, shard_size, retain_graph=retain_graph):
  File "/home/qiansh/data2text/Data2TextWithAuxiliarySupervision/onmt/Loss.py", line 299, in shards
    torch.autograd.backward(inputs, grads, retain_graph=retain_graph)
  File "/home/qiansh/anaconda3/envs/qsh/lib/python3.9/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1200, 6
00]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that f
ailed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by liang8qi** [comment]
您好，方便提供一下你的Python和Pytorch版本吗？

**Comment by liang8qi** [comment]
> 

您好，方便提供一下Python和Pytorch版本吗？

**Comment by Hans-2019** [comment]
python是3.97，torch是'1.7.1+cu110'，cuda是11.0

**Comment by liang8qi** [comment]
> 
你好，我们发现使用pytorch 1.7.1确实会出现上述问题，将pytorch版本降为1.2.0可正常运行，请务必保证
`
nltk==3.4.5
torchtext==0.2.3
torch==1.2
`
由于提供的依赖[3.7.requirements.txt](https://github.com/liang8qi/Data2TextWithAuxiliarySupervision/blob/main/3.7.requirements.txt)包含过多不必要的包，后续会对其进行精简。

**Comment by liang8qi** [comment]
The problem can be solved by installing torch==1.2
