### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by yigguo** [liang8qi/Data2TextWithAuxiliarySupervision#2]
作者你好，我最近跑你的代码，但是在跑train.sh会有如下的报错：
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    main()
  File "train.py", line 520, in main
    fields = load_fields(first_dataset, data_type, checkpoint, cal_indices=opt.cal_indices)
  File "train.py", line 404, in load_fields
    fields = dict([(k, f) for (k, f) in fields
TypeError: 'NoneType' object is not iterable

主要就是变量fields的问题，代码里说fields不能迭代，而我debug的时候fields是空的，这个问题改了好久也没有解决，实在是没有办法了麻烦一下你，提前谢谢了

**Comment by yigguo** [comment]
![屏幕截图 2023-11-14 220749](https://github.com/liang8qi/Data2TextWithAuxiliarySupervision/assets/104619915/6efa36ff-0287-45b8-93d6-681c0775d6d4)
